---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-distribution-updater
  labels:
    app: steam-distribution-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steam-distribution-updater
  template:
    metadata:
      labels:
        app: steam-distribution-updater
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: steam-distribution-updater
        image: gameye/steam-distribution-updater
        args:
          - run
          - config/$(CONFIG_NAME).yaml
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: environment
                key: NODE_ENV
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: environment
                key: DEBUG
          - name: CIRCLE_API_USER_TOKEN
            valueFrom:
              secretKeyRef:
                name: environment
                key: CIRCLE_API_USER_TOKEN
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: steam-distribution-updater
                key: SENTRY_DSN
          - name: CONFIG_NAME
            valueFrom:
              secretKeyRef:
                name: steam-distribution-updater
                key: CONFIG_NAME
