---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-distribution-updater
  labels:
    app: steam-distribution-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steam-distribution-updater
  template:
    metadata:
      labels:
        app: steam-distribution-updater
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: steam-distribution-updater
        image: gameye/steam-distribution-updater
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: environment
                key: NODE_ENV
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: environment
                key: DEBUG
          - name: OCI_PACKAGE_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: OCI_PACKAGE_ENDPOINT
                name: environment
          - name: CIRCLE_API_USER_TOKEN
            valueFrom:
              secretKeyRef:
                name: environment
                key: CIRCLE_API_USER_TOKEN
          - name: STEAM_DISTRIBUTION_UPDATER_CONFIG
            valueFrom:
              secretKeyRef:
                name: environment
                key: STEAM_DISTRIBUTION_UPDATER_CONFIG
