version: 2

jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: >
          docker login
          --username $DOCKER_USERNAME
          --password $DOCKER_PASSWORD
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run:
          environment:
            NVM_DIR: /opt/circleci/.nvm
          command: |
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 12
            nvm alias default 12
            npm install
            npm run lint
            npm run coverage
      - store_artifacts:
          path: coverage/lcov-report
  push:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run: >
          docker login
          --username $DOCKER_USERNAME
          --password $DOCKER_PASSWORD
      - run: >
          docker build
          --build-arg NPM_VERSION=$CIRCLE_TAG
          --build-arg NPM_TOKEN=$NPM_TOKEN
          --tag gameye/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
          .
      - run: docker push gameye/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG

workflows:
  version: 2

  test:
    jobs:
      - test:
          context: authorized
          filters:
            tags:
              only: /.*?/

  push:
    jobs:
      - push:
          context: authorized
          filters:
            branches:
              ignore: /.*?/
            tags:
              # v1.0.0-1 / v1.0.0-pre1 / v1.0.0
              only: /^v\d+\.\d+\.\d+(\-.+)?$/
