branch: master
games:
  - name: csgo
    steamId: 730
    repos:
      - csgo-image
      - csgo-dem-image
      - csgo-get5-image
      - csgo-practice-image
  - name: tf2
    steamId: 440
    repos:
      - tf2-image
      - tf2-serveme-image
