apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-build-trigger
  labels:
    app: steam-build-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steam-build-trigger
  template:
    metadata:
      labels:
        app: steam-build-trigger
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: steam-build-trigger
        image: gameye/steam-build-trigger
        args:
          - run
          - --interval
          - $(INTERVAL)
          - config/$(CONFIG_NAME).yaml
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: environment
                key: NODE_ENV
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: environment
                key: NODE_DEBUG
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: environment
                key: LOG_LEVEL
          - name: INTERVAL
            valueFrom:
              configMapKeyRef:
                name: steam-build-trigger
                key: INTERVAL
          - name: CONFIG_NAME
            valueFrom:
              configMapKeyRef:
                name: steam-build-trigger
                key: CONFIG_NAME
          - name: SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                name: steam-build-trigger
                key: SENTRY_DSN
          - name: CIRCLE_API_USER_TOKEN
            valueFrom:
              secretKeyRef:
                name: steam-build-trigger
                key: CIRCLE_API_USER_TOKEN
          - name: STEAM_API_KEY
            valueFrom:
              secretKeyRef:
                name: steam-build-trigger
                key: STEAM_API_KEY
